# Generated by Django 5.2.5 on 2025-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='documents',
            field=models.JSONField(default=list),
        ),
    ]
