# Generated by Django 5.2.5 on 2025-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0002_conversation_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_citations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_follow_ups',
            field=models.JSONField(default=list),
        ),
    ]
