# Generated by Django 5.2.5 on 2025-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0008_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
